// this is the controller for authentication related stuff
//functions:
//A. getCsrfToken: generate session token for each login session
//B. session login
//C. seesion logout
//D. Check-Auth: verify session cookie and return user info from database (also call user model here)

//NOTE: after deployment, need to add a key to env - see getCsrfToken() comment

const crypto = require('crypto');//for generating random CsrfToken
const { admin } = require("../utils/firebaseAdmin");
const usersModel = require("../models/users");

class authController {
  //A. randomly generate session token for each login session
  getCsrfToken(req, res) {
    //generate the token
    const csrfToken = crypto.randomBytes(32).toString("hex");

    //1. stores it as a cookie (csrfToken)
    res.cookie("csrfToken", csrfToken, {
      httpOnly: false,
      secure: process.env.NODE_ENV === "production", //only sends the cookie over HTTPS in production
      sameSite: "strict", //cookie must come from this site
    });

    //2. also return to frontend
    res.json({ csrfToken });
  }

  //B. session login
  async sessionLogin(req, res) {
    //receive from frontend:
    // 1. idToken (generated by firebase)
    // 2. csrfToken (generated by another backend method called between this one)
    const { idToken, csrfToken } = req.body;

    //compare two copies of token (returned from frontend and stored in the cookie) - if match: safe, so the idToken can be trusted
    if (csrfToken !== req.cookies.csrfToken)
      return res.status(401).send("UNAUTHORIZED");

    //define session lifespan: 5 days, stored in browser
    const expiresIn = 60 * 60 * 24 * 5 * 1000;

    //generate session cookie using idToken
    try {
      const sessionCookie = await admin
        .auth()
        .createSessionCookie(idToken, { expiresIn });
      res.cookie("session", sessionCookie, {
        maxAge: expiresIn,
        httpOnly: true,
        secure: process.env.NODE_ENV === "production",
        sameSite: "strict",
      });
      res.json({ status: "success" });
    } catch {
      res.status(401).send("UNAUTHORIZED");
    }
  }

  //B. session logout
  async sessionLogout(req, res) {
    res.clearCookie("session");
    res.json({ status: "logged out" });
  }

  //D. verify session cookie and return user info
  async checkAuth(req, res) {
    //read cookie
    const sessionCookie = req.cookies.session;
    //check if exists
    if (!sessionCookie) {
      return res.json({ error: "No session" });}

    //asks Firebase to verify it's valid and not expired
    try {
      const decoded = await admin
        .auth()
        .verifySessionCookie(sessionCookie, true);
      //res.json({sessionCookie});

      //get user information in the database through FirebaseUid
      const user = await usersModel.getUserByFirebaseUid(decoded.uid);
      if (!user) return res.status(404).json({ error: "User not found" });
      res.json({
        uid: decoded.uid,
        email: decoded.email,
        userId: user.userId,
        userName: user.userName,
        avatarUrl: user.avatarUrl,
      });
    } catch {
      res.status(401).json({ error: "Invalid session" });
    }
  }

  async authenticate(req, res, next) {
    const sessionCookie = req.cookies.session;
    if (!sessionCookie) return res.json("No session");
    
    try {
      const decoded = await admin
        .auth()
        .verifySessionCookie(sessionCookie, true);
      //get user information in the database through FirebaseUid
      const user = await usersModel.getUserByFirebaseUid(decoded.uid);
      if (!user) return res.status(404).json({ error: "User not found" });
      req.user={
        uid: decoded.uid,
        email: decoded.email,
        ...user
      }
      next();
    } catch(error) {
      console.error(error.code, error.message);
      res.status(401).json({ error: "Invalid session" });
    }
  }
}

module.exports = new authController();